#! /bin/sh

# helps bootstrapping libtool, when checked out from CVS
# requires GNU autoconf and GNU automake
# this is not meant to go into the distributions

rm -f acinclude.m4
ln -s libtool.m4 acinclude.m4
# fake the libtool scripts
touch ltconfig
touch ltmain.sh
touch libtoolize
aclocal
automake --gnu --add-missing
autoconf

for sub in libltdl demo depdemo mdemo cdemo; do
  cd $sub
  rm -f acinclude.m4
  cat ../libtool.m4 > acinclude.m4
  test "$sub" = libltdl && cat ../ltdl.m4 >> acinclude.m4
  aclocal
  test "$sub" = libltdl && autoheader
  automake --gnits --add-missing
  autoconf
  cd ..
done

rm -f ltconfig ltmain.sh libtoolize

exit 0
