#! /bin/sh

# Copyright ????

progname=`echo $0 | sed 's,.*/,,g'`
log_file="${TMPDIR-/tmp}/commitlog.$$"

rm -f $log_file

trap "rm -f \"$log_file\"; exit 1" 1 2 15

if test x"$1" = x"-l"; then
  cvsopt=-l
  shift
else
  cvsopt=
fi

if test $# -gt 1 && test x"$1" = x"-m"; then
  echo "$2" > "$log_file"
  shift; shift
elif test $# -gt 1 && test x"$1" = x"-F"; then
  cat < "$2" > "$log_file" || exit 1
  shift; shift
fi

echo "Checking whether repository is up to date..." >&2
commit=`cvs $cvsopt stat ${1+"$@"} 2>/dev/null | grep Status \
        | egrep -v '(Up-to-date|Locally )'`

if test -n "$commit"; then
  echo "$commit"
  exit 1
fi

echo "Checking commit message..." >&2
if test ! -f "$log_file"; then
  cvs diff -u ChangeLog | grep '+	' | sed 's,\+	,,' > $log_file
fi

if test ! -s "$log_file"; then
  echo "$progname: no ChangeLog entry!" >&2
  exit 1
fi

${PAGER-more} "$log_file" || exit 1

cvs $cvsopt commit -F $log_file ${1+"$@"} || exit 1

rm -f $log_file

exit 0
