#! /bin/sh

# tlibtool - A little test version of libtool.
if test -z "$srcdir"; then
  echo "tlibtool: you must set \`\$srcdir' before running this test program" 1>&2
  exit 1
fi

# Grab all the settings from the generated libtool.
eval "`egrep '^[A-Za-z_][A-Za-z0-9_]*=' ../libtool`"

# Use @VERSION@ so that we can use ../ltmain.in directly.
LTCONFIG_VERSION="@VERSION@"

# Execute the libtool backend.
. $srcdir/../ltmain.in
exit 1
